using System;
using System.Collections.Generic;

namespace WebAccountant.ModelsBase
{
    public partial class Dmdhmua
    {
        public string Id { get; set; } = null!;
        public string? Sodonhang { get; set; }
        public DateTime? Ngaydonhang { get; set; }
        public string? Noidung { get; set; }
        public string? LhmDoituong { get; set; }
        public string? LhmDienthoai { get; set; }
        public string? LhmEmail { get; set; }
        public string? LhcnDoituong { get; set; }
        public string? LhcnDienthoai { get; set; }
        public string? LhcnEmail { get; set; }
        public string? NccMa { get; set; }
        public string? NccTen { get; set; }
        public string? NccDiachi { get; set; }
        public string? NccMst { get; set; }
        public string? NccTknh { get; set; }
        public string? NccDienthoai { get; set; }
        public string? NccNlhTen { get; set; }
        public string? NccNlhDienthoai { get; set; }
        public string? NccFax { get; set; }
        public double SttMh { get; set; }
        public string? Mahh { get; set; }
        public string? Tenhh { get; set; }
        public string? Quycach01 { get; set; }
        public string? Quycach02 { get; set; }
        public string? Quycach03 { get; set; }
        public string? Donggoi01 { get; set; }
        public string? Donggoi02 { get; set; }
        public string? Dvt { get; set; }
        public double Soluong { get; set; }
        public double Dgvnd { get; set; }
        public double Ttvnd { get; set; }
        public double ChietkhauUsd { get; set; }
        public double ChietkhauVnd { get; set; }
        public string? Danhdau { get; set; }
        public double Dgusd { get; set; }
        public string? GhichuDh { get; set; }
        public string? GhichuMh { get; set; }
        public string? Ldh { get; set; }
        public string? LhcnMaDt { get; set; }
        public string? LhcnTenDt { get; set; }
        public string? LhmMaDt { get; set; }
        public string? LhmTenDt { get; set; }
        public double Luong01LkDk { get; set; }
        public double Luong02LkDk { get; set; }
        public double Luong03LkDk { get; set; }
        public string? Madonhang { get; set; }
        public string? MadonhangBan { get; set; }
        public string? Makho { get; set; }
        public string? Mauser { get; set; }
        public DateTime? NgayHd { get; set; }
        public DateTime? Ngaygiaohang { get; set; }
        public DateTime? Ngayhethan { get; set; }
        public double PtChietkhau { get; set; }
        public string? SoHd { get; set; }
        public double SttDonhang { get; set; }
        public double Thueusd { get; set; }
        public double Thuevnd { get; set; }
        public double TonCk { get; set; }
        public double? Trangthai { get; set; }
        public double TsGtgt { get; set; }
        public string? Ttdh { get; set; }
        public double Ttusd { get; set; }
        public double Ttusd01LkDk { get; set; }
        public double Ttusd02LkDk { get; set; }
        public double Ttusd03LkDk { get; set; }
        public double TtusdSauCk { get; set; }
        public double TtusdTt { get; set; }
        public double Ttvnd01LkDk { get; set; }
        public double Ttvnd02LkDk { get; set; }
        public double Ttvnd03LkDk { get; set; }
        public double TtvndSauCk { get; set; }
        public double TtvndTt { get; set; }
        public double Tygia { get; set; }
        public string? Dvt1 { get; set; }
        public string? Dvt2 { get; set; }
        public string? Dvt3 { get; set; }
        public string? IdUpdate { get; set; }
        public double Luong01Cl { get; set; }
        public double Luong01LkCk { get; set; }
        public double Luong01PsTk { get; set; }
        public double Luong02Cl { get; set; }
        public double Luong02LkCk { get; set; }
        public double Luong02PsTk { get; set; }
        public double Luong03Cl { get; set; }
        public double Luong03LkCk { get; set; }
        public double Luong03PsTk { get; set; }
        public double LuongDv1Cl { get; set; }
        public double LuongDv1LkCk { get; set; }
        public double LuongDv1LkDk { get; set; }
        public double LuongDv1PsTk { get; set; }
        public double LuongDv2Cl { get; set; }
        public double LuongDv2LkCk { get; set; }
        public double LuongDv2LkDk { get; set; }
        public double LuongDv2PsTk { get; set; }
        public string? NccEmail { get; set; }
        public double Soluong1 { get; set; }
        public double Soluong2 { get; set; }
        public double Soluong3 { get; set; }
        public double Ttusd01Cl { get; set; }
        public double Ttusd01LkCk { get; set; }
        public double Ttusd01PsTk { get; set; }
        public double Ttusd02Cl { get; set; }
        public double Ttusd02LkCk { get; set; }
        public double Ttusd02PsTk { get; set; }
        public double Ttusd03Cl { get; set; }
        public double Ttusd03LkCk { get; set; }
        public double Ttusd03PsTk { get; set; }
        public double Ttvnd01Cl { get; set; }
        public double Ttvnd01LkCk { get; set; }
        public double Ttvnd02Cl { get; set; }
        public double Ttvnd02LkCk { get; set; }
        public double Ttvnd02PsTk { get; set; }
        public double Ttvnd03Cl { get; set; }
        public double Ttvnd03LkCk { get; set; }
        public double Ttvnd03PsTk { get; set; }
        public string? Dhguid { get; set; }
        public double SttKy { get; set; }
        public string? Chonky { get; set; }
        public string? MaCt { get; set; }
        public string? Tenct { get; set; }
    }
}
