using System;
using System.Collections.Generic;

namespace WebAccountant.ModelsBase
{
    public partial class Dmdhban
    {
        public string Id { get; set; } = null!;
        public string? Ldh { get; set; }
        public double SttDonhang { get; set; }
        public string? Madonhang { get; set; }
        public DateTime? Ngaydonhang { get; set; }
        public DateTime? Ngaygiaohang { get; set; }
        public DateTime? Ngayhethan { get; set; }
        public string? Noidung { get; set; }
        public string? SoHd { get; set; }
        public DateTime? NgayHd { get; set; }
        public string? LhbMaDt { get; set; }
        public string? LhbTenDt { get; set; }
        public string? LhbDienthoai { get; set; }
        public string? LhbEmail { get; set; }
        public string? LhcnMaDt { get; set; }
        public string? LhcnTenDt { get; set; }
        public string? LhcnDienthoai { get; set; }
        public string? LhcnEmail { get; set; }
        public string? NmhMa { get; set; }
        public string? NmhTen { get; set; }
        public string? NmhDiachi { get; set; }
        public string? NmhMst { get; set; }
        public string? NmhTknh { get; set; }
        public string? NmhDienthoai { get; set; }
        public string? NmhNlhTen { get; set; }
        public string? NmhNlhDienthoai { get; set; }
        public string? NmhFax { get; set; }
        public string? NmhEmail { get; set; }
        public double SttMh { get; set; }
        public string? Makho { get; set; }
        public string? Mahh { get; set; }
        public string? Tenhh { get; set; }
        public string? Quycach01 { get; set; }
        public string? Quycach02 { get; set; }
        public string? Quycach03 { get; set; }
        public string? Donggoi01 { get; set; }
        public string? Donggoi02 { get; set; }
        public string? Dvt { get; set; }
        public double Soluong { get; set; }
        public double Dgvnd { get; set; }
        public double Ttvnd { get; set; }
        public double TsGtgt { get; set; }
        public double Thuevnd { get; set; }
        public double TtvndTt { get; set; }
        public double Dgusd { get; set; }
        public double Ttusd { get; set; }
        public double Thueusd { get; set; }
        public double TtusdTt { get; set; }
        public double TonCk { get; set; }
        public double PtChietkhau { get; set; }
        public double ChietkhauVnd { get; set; }
        public double ChietkhauUsd { get; set; }
        public double TtvndSauCk { get; set; }
        public string? GhichuMh { get; set; }
        public string? GhichuDh { get; set; }
        public double Tygia { get; set; }
        public string? Mauser { get; set; }
        public double Luong01LkDk { get; set; }
        public double Luong02LkDk { get; set; }
        public double Luong03LkDk { get; set; }
        public string? Ttdh { get; set; }
        public double? Trangthai { get; set; }
        public string? Danhdau { get; set; }
        public double Ttusd01LkDk { get; set; }
        public double Ttusd02LkDk { get; set; }
        public double Ttusd03LkDk { get; set; }
        public double TtusdSauCk { get; set; }
        public double Ttvnd01LkDk { get; set; }
        public double Ttvnd02LkDk { get; set; }
        public double Ttvnd03LkDk { get; set; }
        public double ChietkhauUsd2 { get; set; }
        public double ChietkhauVnd2 { get; set; }
        public string? Dvt1 { get; set; }
        public string? Dvt2 { get; set; }
        public string? IdUpdate { get; set; }
        public double Luong01Cl { get; set; }
        public double Luong01LkCk { get; set; }
        public double Luong01PsTk { get; set; }
        public double Luong02Cl { get; set; }
        public double Luong02LkCk { get; set; }
        public double Luong02PsTk { get; set; }
        public double Luong03Cl { get; set; }
        public double Luong03LkCk { get; set; }
        public double Luong03PsTk { get; set; }
        public double LuongDv1Cl { get; set; }
        public double LuongDv1LkCk { get; set; }
        public double LuongDv1LkDk { get; set; }
        public double LuongDv1PsTk { get; set; }
        public double LuongDv2Cl { get; set; }
        public double LuongDv2LkCk { get; set; }
        public double LuongDv2LkDk { get; set; }
        public double LuongDv2PsTk { get; set; }
        public string? NmhMatinhthanh { get; set; }
        public string? NmhTentinhthanh { get; set; }
        public double PtChietkhau2 { get; set; }
        public double Soluong1 { get; set; }
        public double Soluong2 { get; set; }
        public double Ttusd01Cl { get; set; }
        public double Ttusd01LkCk { get; set; }
        public double Ttusd01PsTk { get; set; }
        public double Ttusd02Cl { get; set; }
        public double Ttusd02LkCk { get; set; }
        public double Ttusd02PsTk { get; set; }
        public double Ttusd03Cl { get; set; }
        public double Ttusd03LkCk { get; set; }
        public double Ttusd03PsTk { get; set; }
        public double Ttvnd01Cl { get; set; }
        public double Ttvnd01LkCk { get; set; }
        public double Ttvnd01PsTk { get; set; }
        public double Ttvnd02Cl { get; set; }
        public double Ttvnd02LkCk { get; set; }
        public double Ttvnd02PsTk { get; set; }
        public double Ttvnd03Cl { get; set; }
        public double Ttvnd03LkCk { get; set; }
        public double Ttvnd03PsTk { get; set; }
        public string? Malo { get; set; }
        public string? NmhMachinhanh { get; set; }
        public string? NmhTenchinhanh { get; set; }
        public string? Madonhang2 { get; set; }
        public string? NmhDiachiChinhanh { get; set; }
        public string? Dhguid { get; set; }
        public double SttKy { get; set; }
        public string? MaCt { get; set; }
        public string? Tenct { get; set; }
    }
}
